spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/taskpulse}
    username: ${DB_USERNAME:taskpulse}
    password: ${DB_PASSWORD:taskpulse}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    packages-to-scan: tasks,users
    properties:
      hibernate:
        format_sql: true
    show-sql: false
logging:
  level:
    org.springframework.security: DEBUG
server:
  servlet:
    session:
      cookie:
        secure: false # Отключенно пока нет https соединения.
        http-only: true
        same-site: strict
      timeout: 30m
